development:
  adapter: postgresql
  encoding: unicode
  database: COUNTER_APP_development
  pool: 5
  username: stevenfleming
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: COUNTER_APP_test
  pool: 5
  username: stevenfleming
  password: